spring.application.name=products
server.port=8082
#spring.security.oauth2.resourceserver.jwt.issuer-uri= http://localhost:7080/realms/users
spring.security.oauth2.resourceserver.jwt.jwk-set-uri= http://localhost:7080/realms/users/protocol/openid-connect/certs